задание 2
int [] intArray = new int[]{1,2,3,4,5,6,7,8,9}; // массив intArray не инициализирован
try {
   int d = 0;
   double catchedRes1 = intArray[8] / d;
   System.out.println("catchedRes1 = " + catchedRes1);
} catch (ArithmeticException e) {
   System.out.println("Catching exception: " + e);
}



 задание 3
 public static void main(String[] args)throws Exception{
            try {
                int a = 90;
                int b = 3;
                System.out.println(a / b);
                printSum(23, 234);
                int[] abc = { 1, 2 };
                abc[3] = 9;
            }
//            catch (Throwable ex) { //Throwable является базовым классом и не может быть обработан здесь
//                System.out.println("Что-то пошло не так...");
//            }
            catch (NullPointerException ex) {
                System.out.println("Указатель не может указывать на null!");
            } catch (IndexOutOfBoundsException ex) {
                System.out.println("Массив выходит за пределы своего размера!");
            }
        }
        public static void printSum(Integer a, Integer b)
//                throws FileNotFoundException// нет блока try catch в методе printSum
        {
            System.out.println(a + b);
        }
